development:
  adapter: postgresql
  database: chatroom_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: chatroom_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: chatroom_production
  pool: 5
  timeout: 5000